# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'control_robot.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1042, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 10, 256, 131))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_left = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_left.setObjectName("pushButton_left")
        self.horizontalLayout_2.addWidget(self.pushButton_left)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_forward = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_forward.setObjectName("pushButton_forward")
        self.verticalLayout.addWidget(self.pushButton_forward)
        self.pushButton_back = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_back.setObjectName("pushButton_back")
        self.verticalLayout.addWidget(self.pushButton_back)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.pushButton_right = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_right.setStyleSheet("\\\n"
"")
        self.pushButton_right.setObjectName("pushButton_right")
        self.horizontalLayout_2.addWidget(self.pushButton_right)
        self.layoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(50, 280, 173, 27))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_play = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_play.setObjectName("pushButton_play")
        self.horizontalLayout.addWidget(self.pushButton_play)
        self.pushButton_pause = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_pause.setLocale(QtCore.QLocale(QtCore.QLocale.Vietnamese, QtCore.QLocale.Vietnam))
        self.pushButton_pause.setAutoDefault(True)
        self.pushButton_pause.setFlat(False)
        self.pushButton_pause.setObjectName("pushButton_pause")
        self.horizontalLayout.addWidget(self.pushButton_pause)
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(190, 210, 46, 17))
        self.checkBox_2.setObjectName("checkBox_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(310, 10, 640, 480))
        self.label.setMaximumSize(QtCore.QSize(640, 480))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("player.ico"))
        self.label.setObjectName("label")
        self.pushButton_register = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_register.setGeometry(QtCore.QRect(48, 340, 81, 25))
        self.pushButton_register.setObjectName("pushButton_register")
        self.name = QtWidgets.QLineEdit(self.centralwidget)
        self.name.setGeometry(QtCore.QRect(60, 370, 113, 25))
        self.name.setObjectName("name")
        self.pushButton_quit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_quit.setGeometry(QtCore.QRect(60, 430, 89, 25))
        self.pushButton_quit.setObjectName("pushButton_quit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1042, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_left.setText(_translate("MainWindow", "Left"))
        self.pushButton_forward.setText(_translate("MainWindow", "Forward"))
        self.pushButton_back.setText(_translate("MainWindow", "Backward"))
        self.pushButton_right.setText(_translate("MainWindow", "Right"))
        self.pushButton_play.setText(_translate("MainWindow", "Play"))
        self.pushButton_pause.setText(_translate("MainWindow", "Take Photo"))
        self.checkBox_2.setText(_translate("MainWindow", "Auto"))
        self.pushButton_register.setText(_translate("MainWindow", "Register"))
        self.pushButton_quit.setText(_translate("MainWindow", "Quit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
